# Generated by Django 4.2.28 on 2026-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_qrprintsettings_movementcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.department',),
        ),
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.employee',),
        ),
        migrations.CreateModel(
            name='RegistrationRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.registrationrequest',),
        ),
    ]
