# Generated by Django 4.2.28 on 2026-02-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_width_mm', models.PositiveIntegerField(default=70, verbose_name='Ширина карточки (мм)')),
                ('card_height_mm', models.PositiveIntegerField(default=95, verbose_name='Высота карточки (мм)')),
                ('qr_size_px', models.PositiveIntegerField(default=220, verbose_name='Размер QR (px)')),
                ('text_size_px', models.PositiveIntegerField(default=13, verbose_name='Размер текста (px)')),
                ('text_position', models.CharField(choices=[('top', 'Сверху'), ('bottom', 'Снизу'), ('none', 'Скрыть текст')], default='bottom', max_length=10, verbose_name='Позиция текста')),
            ],
            options={
                'verbose_name': 'Настройки печати QR',
                'verbose_name_plural': 'Настройки печати QR',
            },
        ),
        migrations.CreateModel(
            name='MovementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movement_card', to='core.devicehistory', verbose_name='История перемещения')),
            ],
            options={
                'verbose_name': 'Карточка перемещения',
                'verbose_name_plural': 'Карточки перемещения',
                'ordering': ['-created_at'],
            },
        ),
    ]
