# Generated by Django 4.2.28 on 2026-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qrprintsettings_movementcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementCardPrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_width_mm', models.PositiveIntegerField(default=90, verbose_name='Ширина карточки (мм)')),
                ('card_height_mm', models.PositiveIntegerField(default=70, verbose_name='Высота карточки (мм)')),
                ('text_size_px', models.PositiveIntegerField(default=13, verbose_name='Размер текста (px)')),
                ('title_size_px', models.PositiveIntegerField(default=16, verbose_name='Размер заголовка (px)')),
            ],
            options={
                'verbose_name': 'Настройки печати карточек перемещения',
                'verbose_name_plural': 'Настройки печати карточек перемещения',
            },
        ),
        migrations.AddField(
            model_name='movementcard',
            name='from_department',
            field=models.CharField(blank=True, default='—', max_length=150, verbose_name='Отдел (откуда)'),
        ),
        migrations.AddField(
            model_name='movementcard',
            name='from_responsible',
            field=models.CharField(blank=True, default='—', max_length=200, verbose_name='Ответственный (откуда)'),
        ),
        migrations.AddField(
            model_name='movementcard',
            name='to_department',
            field=models.CharField(blank=True, default='—', max_length=150, verbose_name='Отдел (куда)'),
        ),
        migrations.AddField(
            model_name='movementcard',
            name='to_responsible',
            field=models.CharField(blank=True, default='—', max_length=200, verbose_name='Ответственный (куда)'),
        ),
    ]
