# Generated by Django 4.2.28 on 2026-02-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_movementcardprintsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='AdminScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_all_regions', models.BooleanField(default=False, verbose_name='Доступ ко всем регионам')),
                ('can_manage_devices', models.BooleanField(default=True, verbose_name='Управление техникой')),
                ('can_manage_employees', models.BooleanField(default=True, verbose_name='Управление сотрудниками')),
                ('can_manage_qr', models.BooleanField(default=True, verbose_name='Управление QR')),
                ('can_manage_movements', models.BooleanField(default=True, verbose_name='Управление перемещениями')),
                ('can_print_from_bot', models.BooleanField(default=False, verbose_name='Разрешить печать из бота')),
                ('printer_backend', models.CharField(choices=[('none', 'Не использовать'), ('http', 'HTTP endpoint')], default='none', max_length=20, verbose_name='Тип подключения принтера')),
                ('printer_endpoint', models.URLField(blank=True, verbose_name='Сетевой endpoint принтера')),
                ('allowed_regions', models.ManyToManyField(blank=True, to='core.region', verbose_name='Разрешенные регионы')),
                ('django_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник (бот)')),
            ],
            options={
                'verbose_name': 'Права администратора (регион/бот)',
                'verbose_name_plural': 'Права администраторов (регион/бот)',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='device',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.region', verbose_name='Регион'),
        ),
    ]
