# Generated by Django 4.2.28 on 2026-02-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_region_adminscope_department_region_device_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementcard',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_cards', to='core.device', verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='movementcard',
            name='to_department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_cards_to', to='core.department', verbose_name='Отдел (куда)'),
        ),
        migrations.AddField(
            model_name='movementcard',
            name='to_responsible_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_cards_to', to='core.employee', verbose_name='Ответственный (куда)'),
        ),
        migrations.AlterField(
            model_name='movementcard',
            name='history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_card', to='core.devicehistory', verbose_name='История перемещения'),
        ),
    ]
