# Generated by Django 4.2.28 on 2026-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_qrprintsettings_movementcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.computer',),
        ),
        migrations.CreateModel(
            name='PrinterProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.printer',),
        ),
    ]
